[package]
name = "common"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.41"
lazy_static = "1.5.0"
once_cell = "1.21.3"
serde = "1.0.219"
serde_json = "1.0.140"
sha2 = "0.10.9"
tokio = "1.45.0"
tokio-postgres = "0.7.13"
